### ISSUE TITLE
PHP Fatal Error on web panel run

### ISSUE THREAD

**Issue by tnt944445** [webnull/RaspAP#10]
When I run `sudo /usr/share/webapps/raspap/run-webpanel.sh` I get the following output

`PHP Fatal error:  Uncaught exception 'Panthera\Classes\BaseExceptions\FileException' with message 'Path "/usr/share/webapps/raspap/raspap//.content/" is not writable' in /usr/share/webapps/raspap/raspap/vendor/pantheraframework/panthera/lib/Components/Database/Drivers/SQLite3Driver.php:24
Stack trace:
#0 /usr/share/webapps/raspap/raspap/vendor/pantheraframework/panthera/lib/Components/Database/DatabaseDriverLoader.php(79): Panthera\Components\Database\Drivers\SQLite3Driver->connect()
#1 /usr/share/webapps/raspap/raspap/vendor/pantheraframework/panthera/lib/Components/Singleton/CoreSingleton.php(110): Panthera\Components\Database\DatabaseDriverLoader::constructInstance(Object(Panthera\Components\Database\Drivers\SQLite3Driver))
#2 /usr/share/webapps/raspap/raspap/vendor/pantheraframework/panthera/lib/Components/Kernel/Framework.php(167): Panthera\Components\Singleton\CoreSingleton::getInstance()
#3 /usr/share/webapps/raspap/raspap/vendor/pantheraframework/panthera/lib/init.php(76): Panthera\Components\Kernel\Framework->setup(Ar in /usr/share/webapps/raspap/raspap/vendor/pantheraframework/panthera/lib/Components/Database/Drivers/SQLite3Driver.php on line 24`

From the looks of it this project is pretty much dead, but any help will be appreciated.

**Comment by keskad** [comment]
Maybe do:

```
mkdir -p /usr/share/webapps/raspap/raspap//.content/
chown raspap:raspap /usr/share/webapps/raspap/raspap//.content/ -R
chmod 755 /usr/share/webapps/raspap/raspap//.content/ -R
```

**Comment by tnt944445** [comment]
Thank You! That fixed that error. But now I have another error. :cry: 

`~> Deploying a web server configuration
$ /usr/share/webapps/raspap/raspap/vendor/pantheraframework/panthera/lib/Binaries/deploy Build/Environment/Webserver/Php
=======> Running task Build/Environment/Webserver/Php
PHP Fatal error:  Uncaught exception 'Panthera\Classes\BaseExceptions\DatabaseException' with message 'SQLSTATE[HY000]: General error: 1 no such table: configuration, SQL: INSERT INTO configuration (configuration_key, configuration_value, configuration_section, configuration_is_json) VALUES (:key, :value, :section, :isJson)' in /usr/share/webapps/raspap/raspap/vendor/pantheraframework/panthera/lib/Components/Database/Drivers/CommonPDODriver.php:451
Stack trace:
#0 /usr/share/webapps/raspap/raspap/vendor/pantheraframework/panthera/lib/Components/Configuration/Configuration.php(329): Panthera\Components\Database\Drivers\CommonPDODriver->query('INSERT INTO con...', Array)
#1 /usr/share/webapps/raspap/raspap/vendor/pantheraframework/panthera/lib/Deployment/Build/Environment/Webserver/PhpTask.php(22): Panthera\Components\Configuration\Configuration->save()
#2 /usr/share/webapps/raspap/raspap/vendor/pantheraframework/panthera/lib/Binaries/deploy(385): Panthera\Deployment\Build\Environment\Webserver\PhpTask->execute(Object(Panthera\B in /usr/share/webapps/raspap/raspap/vendor/pantheraframework/panthera/lib/Components/Database/Drivers/CommonPDODriver.php on line 451
PHP Fatal error:  Uncaught exception 'RuntimeException' with message 'Child process returned with code 255' in /usr/share/webapps/raspap/raspap/vendor/pantheraframework/panthera/lib/Components/CommandLine/Application.php:415
Stack trace:
#0 /usr/share/webapps/raspap/raspap/vendor/pantheraframework/panthera/lib/Binaries/webserver(100): Panthera\Components\CommandLine\Application->exec('%PF2_PATH%/Bina...', 'passthru', true)`

**Comment by keskad** [comment]
Did you use ./install.sh?

Install.sh is placing installed application in /usr/share/webapps/raspap that should be ready to use.

If you use install.sh and it dont work then please try:

```
cd /usr/share/webapps/raspap/raspap
sudo -u raspap ./vendor/pantheraframework/panthera/lib/Binaries/deploy Build/Database/ConfigurePhinx
sudo -u raspap ./vendor/pantheraframework/panthera/lib/Binaries/deploy Build/Database/Migrate
```
